# Generate FAQ for README

This notebook shows how to generate multilingual FAQ drafts from a source markdown document.

In [1]:
import json

import pandas as pd
from openai import OpenAI
from pydantic import BaseModel, Field

import openaivec
from openaivec import pandas_ext

openaivec.set_client(OpenAI())

openaivec.set_responses_model("gpt-5.4")

In [2]:
docs_df: pd.DataFrame = pd.DataFrame(
    {"title": "readme", "body": [open("../../README.md").read()]}
)
docs_df

    title                                               body
0  readme  # openaivec\n\nAI text processing for pandas a...

In [3]:
class Question(BaseModel):
    question: str = Field(description="The question to ask the model.")
    answer: str = Field(description="The answer to the question.")

class Section(BaseModel):
    title: str = Field(description="The title of the section.")
    content: str = Field(description="The content of the section.")
    questions: list[Question] = Field(description="List of questions and answers related to the section.")

class Document(BaseModel):
    sections: list[Section] = Field(description="List of sections in the document.")

In [4]:
sections_df = docs_df.pipe(
    lambda df: df
    .assign(
        section=lambda df: df["body"].ai.responses(
            instructions="""
            Generate a list of FAQ for each section of the document.
            Break down the document into as many detailed sections as possible,
            regardless of markdown format.
            """,
            response_format=Document
        )
        .map(lambda x: x.sections)
    )
    .drop(columns=["body"])
    .explode("section")
    .ai.extract("section")
)

sections_df

Processing batches:   0%|          | 0/1 [00:00<?, ?item/s]

,title,section_title,section_content,section_questions
0,readme,Project Title,openaivec is a library for AI text processing ...,"[{'question': 'What is openaivec?', 'answer': ..."
0,readme,Contributor Guidelines Reference,The document links to contributor guidelines i...,[{'question': 'Where are the contributor guide...
0,readme,Quick Start Overview,The quick start shows how to install openaivec...,"[{'question': 'How do I install openaivec?', '..."
0,readme,Quick Start Installation,Installation is done with pip using the comman...,[{'question': 'What is the installation comman...
0,readme,Quick Start pandas Example,"The example imports os, pandas, and openaivec'...",[{'question': 'How do I use openaivec with a p...
...,...,...,...,...
0,readme,Additional Resource: Survey Data Transformation,A tutorial is provided for transforming unstru...,[{'question': 'Is there an example for survey ...
0,readme,Additional Resource: Async Processing Examples,A tutorial is provided for high-performance as...,[{'question': 'Are there dedicated async workf...
0,readme,Additional Resource: FAQ Generation,A tutorial is provided for automatically gener...,[{'question': 'Is there an example for generat...
0,readme,Additional Resource: All Examples,A complete collection of tutorials and use cas...,[{'question': 'Where can I browse all openaive...
0,readme,Community,The project has a Discord community for suppor...,[{'question': 'Is there a community for openai...

In [5]:
questions_df: pd.DataFrame = sections_df.pipe(
    lambda df: df
    .drop(columns=["section_content"])
    .explode("section_questions")
    .ai.extract("section_questions")
    .reset_index(drop=True)
)

In [6]:
from IPython.display import Markdown, display

display(Markdown(questions_df.to_markdown()))

|     | title   | section_title                                     | section_questions_question                                                                  | section_questions_answer                                                                                                                                     |
|----:|:--------|:--------------------------------------------------|:--------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------|
|   0 | readme  | Project Title                                     | What is openaivec?                                                                          | openaivec is a Python library for vectorized AI text processing across pandas and Spark.                                                                     |
|   1 | readme  | Project Title                                     | What problem does openaivec solve?                                                          | It helps you run the same prompt over many inputs efficiently using batching, caching, and deduplication.                                                    |
|   2 | readme  | Project Title                                     | Which data tools does openaivec support?                                                    | It supports pandas and Apache Spark.                                                                                                                         |
|   3 | readme  | Contributor Guidelines Reference                  | Where are the contributor guidelines located?                                               | They are linked in AGENTS.md.                                                                                                                                |
|   4 | readme  | Contributor Guidelines Reference                  | Is there a dedicated contribution guide reference in the document?                          | Yes, the document references contributor guidelines through AGENTS.md.                                                                                       |
|   5 | readme  | Quick Start Overview                              | How do I install openaivec?                                                                 | Install it with pip using `pip install openaivec`.                                                                                                           |
|   6 | readme  | Quick Start Overview                              | What does the quick start example demonstrate?                                              | It demonstrates using pandas with the `.ai.responses()` accessor to translate fruit names into French.                                                       |
|   7 | readme  | Quick Start Overview                              | Do I need to set an API key before using openaivec?                                         | Yes, the example sets `OPENAI_API_KEY` in the environment before calling the API.                                                                            |
|   8 | readme  | Quick Start Installation                          | What is the installation command for openaivec?                                             | Use `pip install openaivec`.                                                                                                                                 |
|   9 | readme  | Quick Start Installation                          | Do I need a package manager other than pip to install openaivec?                            | The quick start shows pip as the installation method.                                                                                                        |
|  10 | readme  | Quick Start pandas Example                        | How do I use openaivec with a pandas Series?                                                | Import `pandas_ext`, create a Series, and call `.ai.responses()` with a prompt on the Series.                                                                |
|  11 | readme  | Quick Start pandas Example                        | Why is `from openaivec import pandas_ext` included?                                         | It enables the pandas AI accessors such as `.ai` and `.aio`.                                                                                                 |
|  12 | readme  | Quick Start pandas Example                        | What output does the fruit translation example return?                                      | It returns `['pomme', 'banane', 'cerise']` for apple, banana, and cherry.                                                                                    |
|  13 | readme  | Quick Start Azure and Custom Client Note          | Where can I find Azure OpenAI setup instructions for pandas?                                | See the section titled `pandas authentication options`.                                                                                                      |
|  14 | readme  | Quick Start Azure and Custom Client Note          | Where are custom client setup instructions documented?                                      | They are referenced in the `pandas authentication options` section.                                                                                          |
|  15 | readme  | Pandas Tutorial Link                              | Is there a full pandas tutorial for openaivec?                                              | Yes, a pandas tutorial is available on GitHub Pages.                                                                                                         |
|  16 | readme  | Pandas Tutorial Link                              | Where is the pandas tutorial hosted?                                                        | It is hosted at `https://microsoft.github.io/openaivec/examples/pandas/`.                                                                                    |
|  17 | readme  | Benchmarks Overview                               | What does the benchmark measure?                                                            | It measures execution time for processing 100 numeric strings into integer literals using `Series.aio.responses`.                                            |
|  18 | readme  | Benchmarks Overview                               | Which model was used in the benchmark?                                                      | The benchmark used `gpt-5.1`.                                                                                                                                |
|  19 | readme  | Benchmarks Overview                               | What is the main takeaway from the benchmark?                                               | Batching removes most HTTP overhead, and concurrency reduces total runtime further.                                                                          |
|  20 | readme  | Benchmark Mode: Serial                            | What settings define serial benchmark mode?                                                 | Serial mode uses `batch_size=1` and `max_concurrency=1`.                                                                                                     |
|  21 | readme  | Benchmark Mode: Serial                            | How long did serial mode take in the benchmark?                                             | It took about 141 seconds.                                                                                                                                   |
|  22 | readme  | Benchmark Mode: Batching                          | What settings define batching benchmark mode?                                               | It uses the default `batch_size` and `max_concurrency=1`.                                                                                                    |
|  23 | readme  | Benchmark Mode: Batching                          | How long did batching mode take?                                                            | It took about 15 seconds.                                                                                                                                    |
|  24 | readme  | Benchmark Mode: Concurrent Batching               | What settings define concurrent batching mode?                                              | It uses the default `batch_size` and default `max_concurrency`.                                                                                              |
|  25 | readme  | Benchmark Mode: Concurrent Batching               | How long did concurrent batching take?                                                      | It took about 6 seconds.                                                                                                                                     |
|  26 | readme  | Benchmark Mode: Concurrent Batching               | Why is concurrent batching faster than batching alone?                                      | Because it overlaps batched requests using concurrency while still producing one output per input.                                                           |
|  27 | readme  | Contents Navigation                               | What major topics are covered in the document?                                              | It covers project motivation, workflows, authentication, Spark, prompting, Fabric, contributing, resources, and community.                                   |
|  28 | readme  | Contents Navigation                               | Does the document include both pandas and Spark guidance?                                   | Yes, it includes separate sections for both pandas and Spark usage and authentication.                                                                       |
|  29 | readme  | Why openaivec? Overview                           | Why would someone choose openaivec?                                                         | Because it provides convenient pandas and Spark integrations, optimized batching, caching, retries, reasoning support, and reusable task and prompt tooling. |
|  30 | readme  | Why openaivec? Overview                           | Is openaivec designed only for small local data tasks?                                      | No, it also supports Spark UDFs and production-scale ETL scenarios.                                                                                          |
|  31 | readme  | Why openaivec?: pandas Accessors                  | What are `.ai` and `.aio` in openaivec?                                                     | They are pandas accessors for synchronous and asynchronous AI operations.                                                                                    |
|  32 | readme  | Why openaivec?: pandas Accessors                  | Why are the pandas accessors useful?                                                        | They keep AI workflows inside familiar pandas patterns.                                                                                                      |
|  33 | readme  | Why openaivec?: Batch Optimization                | What do `BatchCache` and `AsyncBatchCache` do?                                              | They optimize batch requests by coalescing calls, deduplicating prompts, preserving output order, and handling failures cleanly.                             |
|  34 | readme  | Why openaivec?: Batch Optimization                | Does openaivec preserve output order during batching?                                       | Yes, it preserves the original order of outputs.                                                                                                             |
|  35 | readme  | Why openaivec?: Batch Optimization                | How does openaivec behave on batch failure?                                                 | It releases waiters even when upstream errors occur.                                                                                                         |
|  36 | readme  | Why openaivec?: Reasoning and Structured Outputs  | Does openaivec support reasoning models?                                                    | Yes, it supports reasoning models using semantics that mirror the OpenAI SDK.                                                                                |
|  37 | readme  | Why openaivec?: Reasoning and Structured Outputs  | Can openaivec handle structured outputs?                                                    | Yes, it supports structured outputs with Pydantic `response_format`.                                                                                         |
|  38 | readme  | Why openaivec?: Caching and Retries               | Does openaivec include caching?                                                             | Yes, it includes built-in caching features.                                                                                                                  |
|  39 | readme  | Why openaivec?: Caching and Retries               | Can pandas and async workflows share caches?                                                | Yes, they can share caches explicitly.                                                                                                                       |
|  40 | readme  | Why openaivec?: Caching and Retries               | How does Spark handle repeated inputs?                                                      | Spark UDFs deduplicate repeated inputs within each partition.                                                                                                |
|  41 | readme  | Why openaivec?: Production and Prompt Tooling     | Does openaivec include prompt-building tools?                                               | Yes, it includes tools like `FewShotPromptBuilder` and `improve`.                                                                                            |
|  42 | readme  | Why openaivec?: Production and Prompt Tooling     | Are there prebuilt tasks in openaivec?                                                      | Yes, it ships a task library with curated prompts and validated outputs.                                                                                     |
|  43 | readme  | Why openaivec?: Production and Prompt Tooling     | Can openaivec support production ETL workflows?                                             | Yes, Spark UDFs and Fabric guidance are intended to help move notebook workflows into production-scale ETL.                                                  |
|  44 | readme  | Overview                                          | What is meant by vectorized OpenAI batch processing?                                        | It means handling many inputs in grouped calls rather than making one API request per input.                                                                 |
|  45 | readme  | Overview                                          | Does openaivec require a specific Python version?                                           | Yes, it requires Python 3.10 or newer.                                                                                                                       |
|  46 | readme  | Overview                                          | Can prompts be reused across pandas and async workflows?                                    | Yes, shared-cache helpers can reuse prompts across both.                                                                                                     |
|  47 | readme  | Core Workflows Overview                           | What workflows does openaivec support?                                                      | It supports direct API usage, pandas integration, reasoning-model usage, task-based workflows, async processing, and Spark UDFs.                             |
|  48 | readme  | Core Workflows Overview                           | Is pandas the only way to use openaivec?                                                    | No, you can also use direct API clients, async accessors, and Spark UDF helpers.                                                                             |
|  49 | readme  | Direct API Usage                                  | How do I use openaivec directly without pandas?                                             | Create a `BatchResponses` client with `BatchResponses.of(...)` and call `.parse()` on a list of inputs.                                                      |
|  50 | readme  | Direct API Usage                                  | Why would I choose direct API usage?                                                        | It gives maximum control over batch client configuration and processing behavior.                                                                            |
|  51 | readme  | Direct API Usage                                  | What configuration options are shown in the direct API example?                             | The example sets the OpenAI client, model name, system message, and uses the default automatic batch size.                                                   |
|  52 | readme  | Direct API Usage: BatchResponses Example          | What class is used for direct batch response processing?                                    | `BatchResponses` is used for direct batch response processing.                                                                                               |
|  53 | readme  | Direct API Usage: BatchResponses Example          | What model is used in the direct API example?                                               | The example uses `gpt-5.1`.                                                                                                                                  |
|  54 | readme  | Direct API Usage: BatchResponses Example          | What result is expected from the direct parse example?                                      | The expected result is `['bear family', 'rabbit family', 'koala family']`.                                                                                   |
|  55 | readme  | Direct API Tutorial Link                          | Is there a full tutorial for direct or pandas-style workflows?                              | Yes, the document links to a complete tutorial at the examples site.                                                                                         |
|  56 | readme  | pandas Authentication Options Overview            | When should I configure pandas authentication?                                              | Before using `.ai` or `.aio` accessors.                                                                                                                      |
|  57 | readme  | pandas Authentication Options Overview            | What authentication options are available for pandas?                                       | OpenAI API key, Azure OpenAI API key, Azure OpenAI with Entra ID, and custom client setup.                                                                   |
|  58 | readme  | pandas Authentication: OpenAI API Key             | How do I authenticate openaivec with OpenAI for pandas?                                     | Set `OPENAI_API_KEY` in your environment.                                                                                                                    |

In [7]:
ja_questions_df: pd.DataFrame = questions_df.pipe(
    lambda df: df
    .ai.responses(
        instructions="""
        Translate given json into japanese with same schema.
        Just return the json without any additional text.
        """
    )
    .map(json.loads)
    .ai.extract()
)

Processing batches:   0%|          | 0/149 [00:00<?, ?item/s]

In [8]:
display(Markdown(ja_questions_df.to_markdown()))

|     | record_title   | record_section_title                                      | record_section_questions_question                                                           | record_section_questions_answer                                                                                                                           |
|----:|:---------------|:----------------------------------------------------------|:--------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------|
|   0 | readme         | プロジェクトタイトル                                      | openaivecとは何ですか？                                                                     | openaivecは、pandasとSpark全体でベクトル化されたAIテキスト処理を行うためのPythonライブラリです。                                                          |
|   1 | readme         | プロジェクトタイトル                                      | openaivecはどのような問題を解決しますか？                                                   | バッチ処理、キャッシュ、重複排除を使って、多くの入力に対して同じプロンプトを効率的に実行できるようにします。                                              |
|   2 | readme         | プロジェクトタイトル                                      | openaivecはどのデータツールをサポートしていますか？                                         | pandasとApache Sparkをサポートしています。                                                                                                                |
|   3 | readme         | コントリビューターガイドライン参照                        | コントリビューターガイドラインはどこにありますか？                                          | AGENTS.mdにリンクされています。                                                                                                                           |
|   4 | readme         | コントリビューターガイドライン参照                        | この文書には専用のコントリビューションガイド参照がありますか？                              | はい、この文書ではAGENTS.mdを通じてコントリビューターガイドラインを参照しています。                                                                       |
|   5 | readme         | クイックスタート概要                                      | openaivecをインストールするにはどうすればよいですか？                                       | `pip install openaivec` を使ってpipでインストールします。                                                                                                 |
|   6 | readme         | クイックスタート概要                                      | クイックスタートの例では何を示していますか？                                                | `.ai.responses()` アクセサを使って、pandasで果物の名前をフランス語に翻訳する方法を示しています。                                                          |
|   7 | readme         | クイックスタート概要                                      | openaivecを使う前にAPIキーを設定する必要がありますか？                                      | はい、この例ではAPIを呼び出す前に環境変数に `OPENAI_API_KEY` を設定しています。                                                                           |
|   8 | readme         | クイックスタートのインストール                            | openaivecのインストールコマンドは何ですか？                                                 | `pip install openaivec` を使用します。                                                                                                                    |
|   9 | readme         | クイックスタートのインストール                            | openaivecをインストールするのにpip以外のパッケージマネージャーは必要ですか？                | クイックスタートでは、インストール方法としてpipが示されています。                                                                                         |
|  10 | readme         | クイックスタート pandas の例                              | pandas の Series で openaivec を使うにはどうすればよいですか？                              | `pandas_ext` をインポートし、Series を作成して、その Series に対してプロンプト付きで `.ai.responses()` を呼び出します。                                   |
|  11 | readme         | クイックスタート pandas の例                              | なぜ `from openaivec import pandas_ext` を含めるのですか？                                  | `.ai` や `.aio` などの pandas AI アクセサを有効にするためです。                                                                                           |
|  12 | readme         | クイックスタート pandas の例                              | 果物の翻訳例はどのような出力を返しますか？                                                  | apple、banana、cherry に対して `['pomme', 'banane', 'cerise']` を返します。                                                                               |
|  13 | readme         | クイックスタート Azure とカスタムクライアントに関する注記 | pandas 向けの Azure OpenAI セットアップ手順はどこで確認できますか？                         | `pandas authentication options` というタイトルのセクションを参照してください。                                                                            |
|  14 | readme         | クイックスタート Azure とカスタムクライアントに関する注記 | カスタムクライアントのセットアップ手順はどこに記載されていますか？                          | `pandas authentication options` セクションで参照されています。                                                                                            |
|  15 | readme         | Pandas チュートリアルへのリンク                           | openaivec には pandas の完全なチュートリアルがありますか？                                  | はい、GitHub Pages で pandas チュートリアルが公開されています。                                                                                           |
|  16 | readme         | Pandas チュートリアルへのリンク                           | pandas チュートリアルはどこでホストされていますか？                                         | `https://microsoft.github.io/openaivec/examples/pandas/` でホストされています。                                                                           |
|  17 | readme         | ベンチマークの概要                                        | このベンチマークは何を測定していますか？                                                    | `Series.aio.responses` を使用して、100 個の数値文字列を整数リテラルに変換する処理の実行時間を測定しています。                                             |
|  18 | readme         | ベンチマークの概要                                        | ベンチマークではどのモデルが使用されましたか？                                              | ベンチマークでは `gpt-5.1` が使用されました。                                                                                                             |
|  19 | readme         | ベンチマークの概要                                        | このベンチマークの主なポイントは何ですか？                                                  | バッチ処理により HTTP のオーバーヘッドの大部分が取り除かれ、さらに並行処理によって総実行時間が短縮されます。                                              |
|  20 | readme         | ベンチマークモード: シリアル                              | シリアルベンチマークモードを定義する設定は何ですか？                                        | シリアルモードでは `batch_size=1` と `max_concurrency=1` を使用します。                                                                                   |
|  21 | readme         | ベンチマークモード: シリアル                              | ベンチマークでシリアルモードにはどれくらい時間がかかりましたか？                            | 約141秒かかりました。                                                                                                                                     |
|  22 | readme         | ベンチマークモード: バッチ処理                            | バッチ処理ベンチマークモードを定義する設定は何ですか？                                      | デフォルトの `batch_size` と `max_concurrency=1` を使用します。                                                                                           |
|  23 | readme         | ベンチマークモード: バッチ処理                            | バッチ処理モードにはどれくらい時間がかかりましたか？                                        | 約15秒かかりました。                                                                                                                                      |
|  24 | readme         | ベンチマークモード: 同時バッチ処理                        | 同時バッチ処理モードを定義する設定は何ですか？                                              | デフォルトの `batch_size` とデフォルトの `max_concurrency` を使用します。                                                                                 |
|  25 | readme         | ベンチマークモード: 同時バッチ処理                        | 同時バッチ処理にはどれくらい時間がかかりましたか？                                          | 約6秒かかりました。                                                                                                                                       |
|  26 | readme         | ベンチマークモード: 同時バッチ処理                        | なぜ同時バッチ処理はバッチ処理単独より速いのですか？                                        | 並行処理を使ってバッチ化されたリクエストを重ね合わせながら、入力ごとに1つの出力を生成し続けるためです。                                                   |
|  27 | readme         | 目次ナビゲーション                                        | このドキュメントではどのような主要トピックが扱われていますか？                              | プロジェクトの動機、ワークフロー、認証、Spark、プロンプティング、Fabric、コントリビューション、リソース、コミュニティを扱っています。                     |
|  28 | readme         | 目次ナビゲーション                                        | このドキュメントには pandas と Spark の両方に関するガイダンスが含まれていますか？           | はい、pandas と Spark の使用方法および認証について、それぞれ独立したセクションが含まれています。                                                          |
|  29 | readme         | なぜ openaivec か？ 概要                                  | なぜ openaivec を選ぶのでしょうか？                                                         | 便利な pandas および Spark 統合、最適化されたバッチ処理、キャッシュ、リトライ、推論サポート、再利用可能なタスクおよびプロンプトツールを提供するためです。 |
|  30 | readme         | なぜopenaivecなのか？ 概要                                | openaivecは小規模なローカルデータのタスク専用に設計されていますか？                         | いいえ、Spark UDFや本番規模のETLシナリオにも対応しています。                                                                                              |
|  31 | readme         | なぜopenaivecなのか？: pandasアクセサ                     | openaivecにおける`.ai`と`.aio`とは何ですか？                                                | これらは、同期および非同期のAI操作のためのpandasアクセサです。                                                                                            |
|  32 | readme         | なぜopenaivecなのか？: pandasアクセサ                     | pandasアクセサはなぜ便利なのですか？                                                        | AIワークフローを、使い慣れたpandasのパターンの中に保つことができます。                                                                                    |
|  33 | readme         | なぜopenaivecなのか？: バッチ最適化                       | `BatchCache`と`AsyncBatchCache`は何をしますか？                                             | 呼び出しの集約、プロンプトの重複排除、出力順序の維持、失敗時の適切な処理によって、バッチリクエストを最適化します。                                        |
|  34 | readme         | なぜopenaivecなのか？: バッチ最適化                       | openaivecはバッチ処理中に出力順序を維持しますか？                                           | はい、出力の元の順序を維持します。                                                                                                                        |
|  35 | readme         | なぜopenaivecなのか？: バッチ最適化                       | バッチ処理が失敗した場合、openaivecはどのように動作しますか？                               | 上流でエラーが発生した場合でも、待機中の処理を解放します。                                                                                                |
|  36 | readme         | なぜopenaivecなのか？: 推論と構造化出力                   | openaivecは推論モデルをサポートしていますか？                                               | はい、OpenAI SDKのセマンティクスを反映した形で推論モデルをサポートしています。                                                                            |
|  37 | readme         | なぜopenaivecなのか？: 推論と構造化出力                   | openaivecは構造化出力を扱えますか？                                                         | はい、Pydanticの`response_format`による構造化出力をサポートしています。                                                                                   |
|  38 | readme         | なぜopenaivecなのか？: キャッシュとリトライ               | openaivecにはキャッシュ機能が含まれていますか？                                             | はい、組み込みのキャッシュ機能が含まれています。                                                                                                          |
|  39 | readme         | なぜopenaivecなのか？: キャッシュとリトライ               | pandasと非同期ワークフローでキャッシュを共有できますか？                                    | はい、明示的にキャッシュを共有できます。                                                                                                                  |
|  40 | readme         | なぜ openaivec なのか？: キャッシュとリトライ             | Spark は繰り返し入力をどのように処理しますか？                                              | Spark UDF は各パーティション内で繰り返し入力を重複排除します。                                                                                            |
|  41 | readme         | なぜ openaivec なのか？: 本番運用とプロンプトツール       | openaivec にはプロンプト構築ツールが含まれていますか？                                      | はい、`FewShotPromptBuilder` や `improve` のようなツールが含まれています。                                                                                |
|  42 | readme         | なぜ openaivec なのか？: 本番運用とプロンプトツール       | openaivec にはあらかじめ用意されたタスクがありますか？                                      | はい、厳選されたプロンプトと検証済みの出力を備えたタスクライブラリが含まれています。                                                                      |
|  43 | readme         | なぜ openaivec なのか？: 本番運用とプロンプトツール       | openaivec は本番 ETL ワークフローをサポートできますか？                                     | はい、Spark UDF と Fabric のガイダンスは、ノートブックのワークフローを本番規模の ETL に移行するのに役立つことを意図しています。                           |
|  44 | readme         | 概要                                                      | ベクトル化された OpenAI バッチ処理とはどういう意味ですか？                                  | これは、入力ごとに 1 回ずつ API リクエストを行うのではなく、複数の入力をまとめて処理することを意味します。                                                |
|  45 | readme         | 概要                                                      | openaivec には特定の Python バージョンが必要ですか？                                        | はい、Python 3.10 以降が必要です。                                                                                                                        |
|  46 | readme         | 概要                                                      | プロンプトは pandas と async のワークフロー間で再利用できますか？                           | はい、共有キャッシュヘルパーにより、その両方でプロンプトを再利用できます。                                                                                |
|  47 | readme         | コアワークフローの概要                                    | openaivec はどのようなワークフローをサポートしていますか？                                  | 直接 API 利用、pandas 統合、推論モデルの利用、タスクベースのワークフロー、非同期処理、Spark UDF をサポートしています。                                    |
|  48 | readme         | コアワークフローの概要                                    | openaivec を使う方法は pandas だけですか？                                                  | いいえ、直接 API クライアント、非同期アクセサー、Spark UDF ヘルパーも使用できます。                                                                       |
|  49 | readme         | 直接 API 利用                                             | pandas を使わずに openaivec を直接使うにはどうすればよいですか？                            | `BatchResponses.of(...)` で `BatchResponses` クライアントを作成し、入力のリストに対して `.parse()` を呼び出します。                                       |
|  50 | readme         | 直接 API 利用                                             | なぜ直接 API 利用を選ぶのですか？                                                           | バッチクライアントの設定や処理動作を最大限に制御できるためです。                                                                                          |
|  51 | readme         | Direct API Usage                                          | 直接APIの例では、どの設定オプションが示されていますか？                                     | この例では、OpenAIクライアント、モデル名、システムメッセージを設定し、デフォルトの自動バッチサイズを使用しています。                                      |
|  52 | readme         | Direct API Usage: BatchResponses Example                  | 直接バッチ応答処理にはどのクラスが使われますか？                                            | 直接バッチ応答処理には`BatchResponses`が使われます。                                                                                                      |
|  53 | readme         | Direct API Usage: BatchResponses Example                  | 直接APIの例では、どのモデルが使われていますか？                                             | この例では`gpt-5.1`が使われています。                                                                                                                     |
|  54 | readme         | Direct API Usage: BatchResponses Example                  | 直接parseの例では、どのような結果が期待されますか？                                         | 期待される結果は`['bear family', 'rabbit family', 'koala family']`です。                                                                                  |
|  55 | readme         | Direct API Tutorial Link                                  | 直接ワークフローまたはpandasスタイルのワークフロー向けの完全なチュートリアルはありますか？  | はい、このドキュメントにはexamplesサイトの完全なチュートリアルへのリンクがあります。                                                                      |
|  56 | readme         | pandas Authentication Options Overview                    | pandasの認証はいつ設定すべきですか？                                                        | `.ai`または`.aio`アクセサを使用する前に設定してください。                                                                                                 |
|  57 | readme         | pandas Authentication Options Overview                    | pandasではどのような認証オプションが利用できますか？                                        | OpenAI APIキー、Azure OpenAI APIキー、Entra IDを使用したAzure OpenAI、そしてカスタムクライアント設定です。                                                |
|  58 | readme         | pandas Authentication: OpenAI API Key                     | pandasでopenaivecをOpenAIに認証するにはどうすればよいですか？                               | 環境変数に`OPENAI_API_KEY`を設定してください。                                                                                                            |
|  59 | readme         | pandas Authentication: OpenAI API Key                     | OpenAI認証に使用される環境変数はどれですか？                                                | `OPENAI_API_KEY`です。                                                                                                                                    |
|  60 | readme         | pandas Authentication: Azure OpenAI API Key               | pandasでAzure OpenAI APIキー認証に必要な環境変数は何ですか？                                | `AZURE_OPENAI_API_KEY`、`AZURE_OPENAI_BASE_URL`、`AZURE_OPENAI_API_VERSION`です。                                                                         |
|  61 | readme         | pandas Authentication: Azure OpenAI API Key               | `/openai/v1/` のAzureベースURLでは、どのAPIバージョンを使うべきですか？                     | `AZURE_OPENAI_API_VERSION="v1"`を使用してください。                                                                                                       |
|  62 | readme         | pandas 認証: Azure OpenAI API キー                        | Azure のベース URL はどのような形式にすべきですか？                                         | `https://YOUR-RESOURCE-NAME.services.ai.azure.com/openai/v1/` のような形式にしてください。                                                                |
|  63 | readme         | pandas 認証: Entra ID を使用した Azure OpenAI             | API キーの代わりに Entra ID で Azure OpenAI を使用するにはどうすればよいですか？            | Azure のベース URL と API バージョンを設定し、環境から `AZURE_OPENAI_API_KEY` を削除します。                                                              |
|  64 | readme         | pandas 認証: Entra ID を使用した Azure OpenAI             | `AZURE_OPENAI_API_KEY` が設定されていない場合、openaivec はどの認証資格情報を使用しますか？ | `DefaultAzureCredential` を使用します。                                                                                                                   |
|  65 | readme         | pandas 認証: カスタムクライアント                         | openaivec でカスタム OpenAI クライアントを使用できますか？                                  | はい、カスタムの同期クライアントと非同期クライアントを設定できます。                                                                                      |
|  66 | readme         | pandas 認証: カスタムクライアント                         | カスタムの同期クライアントを登録するにはどうすればよいですか？                              | `openaivec.set_client(OpenAI())` を呼び出します。                                                                                                         |
|  67 | readme         | pandas 認証: カスタムクライアント                         | カスタムの非同期クライアントを登録するにはどうすればよいですか？                            | `openaivec.set_async_client(AsyncOpenAI())` を呼び出します。                                                                                              |
|  68 | readme         | pandas 統合の概要                                         | DataFrame で openaivec を使用する推奨方法は何ですか？                                       | 認証とデフォルトモデルの設定後に、`.ai.responses()` を使った pandas 統合を使用します。                                                                    |